#!/usr/bin/env bash

# Copyright (C) 2023 modvpn LLC, GPL-3.0
# Copyright (C) 2022 Mullvad VPN AB, GPL-3.0

set -euo pipefail

INSTALL_DIR="/Applications"
LOG_DIR="/var/log/modvpn"
modvpn_DAEMON_PLIST_PATH="/Library/LaunchDaemons/app.modvpn.daemon.plist"

mkdir -p $LOG_DIR
chmod 755 $LOG_DIR

exec 2>&1 > "${LOG_DIR}/preinstall.log"

stop_daemon_and_ui() {
    if [[ -f "${modvpn_DAEMON_PLIST_PATH}" ]]; then
        # Stop Daemon and UI and copy old log file
        launchctl unload -w "${modvpn_DAEMON_PLIST_PATH}" || true
        pkill -x "modvpn-ui" || echo "Failed to stop modvpn-ui" || true
        cp "${LOG_DIR}/modvpn-daemon.log" "$LOG_DIR/previous-modvpn-daemon.log" \
            || echo "Failed to copy old modvpn-daemon log"

    else
        echo "No previous installation found"
    fi
}

create_exclusion_group() {
    # Create a group for modvpn-exclusion
    modvpn_EXCLUSION_GROUP="modvpn-exclusion"
    if ! dscl . -list /Groups | grep $modvpn_EXCLUSION_GROUP; then
    dscl . -create /Groups/$modvpn_EXCLUSION_GROUP \
        || echo "FAILED TO CREATE $modvpn_EXCLUSION_GROUP GROUP"
    fi
    if ! dscl . -read /Groups/$modvpn_EXCLUSION_GROUP | grep PrimaryGroupID; then
    modvpn_EXCLUSION_GID=$(( RANDOM ))
    dscl . -append /Groups/$modvpn_EXCLUSION_GROUP PrimaryGroupID $modvpn_EXCLUSION_GID \
        && echo "Created modvpn-exclusion group with gid $modvpn_EXCLUSION_GID" \
        || echo "FAILED TO CREATE 'modvpn-exclusion' group"
    fi
}

main() {
    create_exclusion_group
    stop_daemon_and_ui
}

main "$@"
